version: '3.9'
services:
  djangoserver:
    build: .
    volumes:
      - .:/app
    ports:
      - '8080:80'
    depends_on:
      - mydb
  mydb:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD: mypassword



